### ISSUE TITLE
[Advice]

### ISSUE THREAD

**Issue by Rayscan321** [Samueli924/chaoxing#236]
**清晰有逻辑的提出问题**
详细内容
我的云服务器的系统为centos7.9，安装宝塔面板后的python3.7.9运行main.py后，显示
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from api.chaoxing import Chaoxing
  File "/usr/local/pyprogram/chaoxing-main/api/chaoxing.py", line 188
    if res := re.search(
            ^
SyntaxError: invalid syntax
查阅资料后发现是我的python版本不支持“ :=”这个语法,请问我该如何解决这个问题（不想升级python，怕升级后与宝塔面板冲突）

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
