### ISSUE TITLE
在Windows平台下运行报错

### ISSUE THREAD

**Issue by Jeremy-cell** [Samueli924/chaoxing#244]
**在Windows平台下运行报错**
在window Dos窗口运行此脚本，显示如下报错：
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\chaoxing-main\chaoxing-main\main.py", line 5, in <module>
    import utils.functions as ft
  File "C:\Users\admin\Downloads\chaoxing-main\chaoxing-main\utils\functions.py", line 5, in <module>
    import maskpass
ModuleNotFoundError: No module named 'maskpass'
-----------------------------------------------------------------
Python version : python-3.10.11-amd64。

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
