### ISSUE TITLE
打开出现错误[BUG反馈]

### ISSUE THREAD

**Issue by SasakiGo** [Samueli924/chaoxing#285]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
PS F:\c\chaoxing> python main.py

F:\c\chaoxing\utils\functions.py:16: SyntaxWarning: invalid escape sequence '\ '
  print("""                                                                                 ,---.-,                         ,--,
Traceback (most recent call last):
  File "F:\c\chaoxing\main.py", line 6, in <module>
    from api.chaoxing import Chaoxing
  File "F:\c\chaoxing\api\chaoxing.py", line 12, in <module>
    import requests
  File "F:\python\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "F:\python\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "F:\python\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "F:\python\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
