### ISSUE TITLE
[BUG反馈] KeyError: 'doublespeed'

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#290]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
```

2023-11-14 22:16 | INFO     | __main__:<module>:60 - 课程列表过滤完毕，当前课程任务数量: 1
2023-11-14 22:16 | INFO     | api.base:get_course_point:101 - 课程章节读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
2023-11-14 22:16 | INFO     | api.base:get_job_list:110 - 章节任务点读取成功...
Traceback (most recent call last):
  File "/home/cx/main.py", line 66, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
  File "/home/cx/api/base.py", line 109, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
  File "/home/cx/api/decode.py", line 91, in decode_course_card
    _job["doublespeed"] = _card["property"]["doublespeed"]
KeyError: 'doublespeed'
```
**运行环境 (请完善以下信息):**
 - 系统：ubuntu
 - Python环境版本:python3.10
 - 运行方式: 源码
 - 代码版本: 0bbf8c2393a0be2a0ce744142005bde021d28d9c

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
可以提供一下课程输出的日志吗

**Comment by Samueli924** [comment]
> > _video_info
> 
> 我应该如何获取_video_info结构呢 在vscode带参数调试python 程序 可以麻烦下您指导下吗
> 
> 我明天再回复您的reply

你可以把base.py的149行改成这样 然后再运行
![image](https://github.com/Samueli924/chaoxing/assets/65054820/12cfbaac-9525-444e-b14f-80ecdf8d5455)

**Comment by Samueli924** [comment]
感谢反馈 已在最新版本修复
