### ISSUE TITLE
[BUG反馈] AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by UPman24** [Samueli924/chaoxing#293]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

1.
```
 decode_course_point
    _course_point["finish_num"] = _soup.select_one("div.chapter_head h2.xs_head_name span").text
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

2.
```
Traceback (most recent call last):
  File "xxxxx/main.py", line 70, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxx/api/base.py", line 109, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

3.
```
Traceback (most recent call last):
  File "xxxxx/main.py", line 70, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxx/api/base.py", line 109, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

我大概也只找到了这些BUG，如果有会补充进来，可能课程不一样错误就不一样

**Comment by Samueli924** [comment]
感谢反馈，已修复。

**Comment by AAlieZZ** [comment]
目前的版本仍有错误：
```
Traceback (most recent call last):
  File "/path/to/chaoxing/main.py", line 67, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
  File "/path/to/chaoxing/api/base.py", line 111, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
TypeError: cannot unpack non-iterable NoneType object
```
