### ISSUE TITLE
[BUG反馈] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#299]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
```
2023-11-17 00:18:10 | INFO     | __main__:<module>:63 - 课程列表过滤完毕，当前课程任务数量: 1
2023-11-17 00:18:10 | INFO     | api.base:get_course_point:103 - 课程章节读取成功...
2023-11-17 00:18:10 | INFO     | api.base:get_job_list:113 - 章节任务点读取成功...
2023-11-17 00:18:11 | INFO     | api.base:get_job_list:113 - 章节任务点读取成功...
2023-11-17 00:18:11 | INFO     | api.base:study_video:156 - 开始任务:第一个视频.mp4, 总时长: 472秒
Traceback (most recent call last):
  File "/home/cx/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cx/main.py", line 78, in <module>
    chaoxing.study_video(course, job, job_info, _speed=speed)
  File "/home/cx/api/base.py", line 160, in study_video
    _isPassed = self.video_progress_log(_session, _course, _job, _job_info, _dtoken, _duration, 0)
  File "/home/cx/api/base.py", line 141, in video_progress_log
    return resp.json()["isPassed"]
  File "/home/cx/.local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~/ main ?1 ❯                                                                
```
**运行环境 (请完善以下信息):**
 - 系统：ubuntu
 - Python环境版本:python3.10
 - 运行方式: 源码
 - 代码版本: 32bc7d88aa47d6448d1180f6ab57259fc8bfb1ce

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by acdiost** [comment]
![image](https://github.com/Samueli924/chaoxing/assets/38416288/2617146f-247c-4a57-a549-8ac1796f800e)

```bash
2023-11-28 20:41:46.146 | INFO     | api.base:study_video:157 - 开始任务:第x集_xxx.mp4, 总时长: 398秒
2023-11-28 20:41:46.217 | INFO     | api.base:video_progress_log:141 - <!doctype html>
<html>

<script>
    _HOST_ = "";
    _CP_ = "";
    _HOST_CP1_ = "";
    // _HOST_CP2_ = _HOST_ + _CP_;
    _HOST_CP2_ = _CP_;
</script><head>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no" />
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0"/>
    <meta charset="utf-8">
    <title>403</title>
    <style>
        *{margin:0;padding:0;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;-webkit-appearance:none;}
        body{font:14px/1.5 微软雅黑;background:#fff;color:#333;-webkit-tap-highlight-color: transparent;}
        ul{list-style-type:none;}
        input,select,textarea{vertical-align:middle; font:14px 微软雅黑; color:#333;}
        a{text-decoration:none;color:#333;}
        table{border-spacing:0px; border-collapse:collapse;width:100%; border:0px;margin:0;padding:0;}
        img{border:0px;}
        em{font-style:normal;}
        .tipsOne{width:100%;margin:0 auto;position:absolute;left:50%;top:50%;transform: translate(-50%, -60%);}
        .tipsOne dl{width:360px;margin:0 auto}
        .tipsOne dl dt{width:360px;height:252px;margin:0 auto}
        .tipsOne dl dt img{display:block;width:100%;height:100%}
        .tipsOne dd{color: #8A8B99;font-size: 16px;margin-top:20px;padding-left:30px;}
        .tipsOne .infoCon{width:360px;margin:0 auto;margin-top:20px;}
        .tipsOne .infoCon p{color: #8A8B99;font-size:16px;line-height:24px;padding-left:30px;}
        @media screen and (max-width: 750px) {
            .tipsOne dl{width:100%;margin:0 auto}
            .tipsOne dl dt{width:220px;height:154px;margin:0 auto}
            .tipsOne dl dt img{display:block;width:100%;height:100%}
            .tipsOne dd{color: #8A8B99;font-size: 16px;margin-top:15px;padding-left:40px;}
            .tipsOne .infoCon{width:100%;margin:0 auto;margin-top:20px;}
            .tipsOne .infoCon p{font-size:16px;color:#999;line-height:24px;padding-left:40px;}
        }
    </style>
</head>
<body>
<div class="tipsOne">
    <dl>
        <dt><img src="https://p.ananas.chaoxing.com/star3/origin/f0daca2712648df3facec46ed51e8b71.png" /></dt>
        <dd>【9011】很抱歉，您没有权限访问这个页面！code=6 </dd>
    </dl>
    <div class="infoCon">
        <p>236731808</p>
        <p>117.154.73.255</p>
        <p>mooc-4243966623-gv8vj</p>
        <p>2023-11-28 20:41:45</p>
    </div>
</div>
</body>
</html>
Traceback (most recent call last):
  File "C:\Users\Desktop\chaoxing-3.0.3\.venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Desktop\chaoxing-3.0.3\main.py", line 78, in <module>
    chaoxing.study_video(course, job, job_info, _speed=speed)
  File "C:\Users\Desktop\chaoxing-3.0.3\api\base.py", line 161, in study_video
    _isPassed = self.video_progress_log(_session, _course, _job, _job_info, _dtoken, _duration, 0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\chaoxing-3.0.3\api\base.py", line 142, in video_progress_log
    return resp.json()["isPassed"]
           ^^^^^^^^^^^
  File "C:\Users\Desktop\chaoxing-3.0.3\.venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by DmTomHL** [comment]
我也有类似问题，请问如何解决

**Comment by Samueli924** [comment]
已修复
