### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by muziliai** [Samueli924/chaoxing#301]
Traceback (most recent call last):
  File "D:\Git\chaoxing\main.py", line 69, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
  File "D:\Git\chaoxing\api\base.py", line 111, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
TypeError: cannot unpack non-iterable NoneType object

**Comment by Samueli924** [comment]
已修复
