### ISSUE TITLE
出现JSON.DECODER错误的朋友请看这条

### ISSUE THREAD

**Issue by Samueli924** [Samueli924/chaoxing#307]
一直以来有很多Issue反馈出现JSON DECODE错误，日志显示403权限不足报错。由于我已经毕业且没有可用的复现环境，希望有能力的朋友可以在出现403错误的时候尝试抓包网页端请求结果并打包日志发送至我的邮箱，或者如果有朋友不介意的话，也可以提供学习通的账号密码，供我更方便的定位报错原因，谢谢帮助。邮箱下附：

samuelchen0204@gmail.com

**Comment by wkz2003** [comment]
目前没有遇到403，就是遇到json decode错误
错误如下：
2023-12-19 23:08:44.956 | INFO     | api.base:study_video:156 - 开始任务:4.4人从哪里来3.0.mp4, 总时长: 759秒
Traceback (most recent call last):
  File "D:\python项目\chaoxing\chaovenv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\wkz\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\wkz\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\wkz\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python项目\chaoxing\chaoxing-main\main.py", line 84, in <module>
    chaoxing.study_video(course, job, job_info, _speed=speed)
  File "D:\python项目\chaoxing\chaoxing-main\api\base.py", line 160, in study_video
    _isPassed = self.video_progress_log(_session, _course, _job, _job_info, _dtoken, _duration, 0)
  File "D:\python项目\chaoxing\chaoxing-main\api\base.py", line 141, in video_progress_log
    return resp.json()["isPassed"]
  File "D:\python项目\chaoxing\chaovenv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by haogaulle** [comment]
今天在使用时发现错误出现原因：

- 向 https://mooc1.chaoxing.com/mooc-ans/multimedia/log/a/ 发起请求时所带的playingtime参数被始终设置为0（是不是测试改的，后来忘记改过来了）

修改：

- 将base.py第141行修改为`f"playingTime={_playingTime}&"`
- 修改后个人个人可正常使用

**Comment by lvguanjun** [comment]
![Uploading image.png…]()
修复如下

**Comment by Samueli924** [comment]
> 今天在使用时发现错误出现原因：
> 
> * 向 https://mooc1.chaoxing.com/mooc-ans/multimedia/log/a/ 发起请求时所带的playingTime参数被始终设置为0（是不是测试的时候改的，后来忘记改过来了）
> 
> 修改：
> 
> * 将base.py第141行修改为`f"playingTime={_playingTime}&"`
> * 修改后个人个人可正常使用

已修复
