### ISSUE TITLE
[BUG反馈] INFO     | api.base:get_course_list:95 - 课程列表读取完毕...之后便是错误

### ISSUE THREAD

**Issue by WuhuVoV** [Samueli924/chaoxing#315]
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    all_course = chaoxing.get_course_list()
  File "C:\Users\WIN11\Desktop\chaoxing-main\api\base.py", line 96, in get_course_list
    course_list = decode_course_list(_resp.text)
  File "C:\Users\WIN11\Desktop\chaoxing-main\api\decode.py", line 10, in decode_course_list
    _soup = BeautifulSoup(_text, "lxml")
  File "C:\Users\WIN11\AppData\Roaming\Python\Python38\site-packages\bs4\__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by WuhuVoV** [comment]
bs4解析网页时报错：bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

原因：不可以使用 BeautifulSoup(html,'html_parser')

解决办法：

1.安装 pip install lxml

2.将BeautifulSoup(html,'html_parser') 改为BeautifulSoup(html,'lxml')

**Comment by 41369ly** [comment]
pip install 执行过吗？BeautifulSoup(html,'html_parser')这行代码在这个仓库中没有出现过啊
