### ISSUE TITLE
[BUG反馈] KeyError: 'type'

### ISSUE THREAD

**Issue by WonderLand33** [Samueli924/chaoxing#329]
**代码报错截图**
```
2024-03-29 08:42:00.326 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:00.522 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:00.884 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:01.024 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:01.225 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:01.514 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:01.755 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:02.029 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:02.235 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:02.486 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:02.673 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:03.031 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:03.236 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:03.523 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:03.700 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
2024-03-29 08:42:04.029 | INFO     | api.base:get_job_list:130 - 章节任务点读取成功...
Traceback (most recent call last):
  File "/Users/champion/Downloads/chaoxing/main.py", line 70, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/champion/Downloads/chaoxing/api/base.py", line 128, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/champion/Downloads/chaoxing/api/decode.py", line 90, in decode_course_card
    if _card["type"] == "video":
       ~~~~~^^^^^^^^
KeyError: 'type'
```

**config.ini**
```

[common]
; 手机号账号(必填)
username = *******

; 登录密码(必填)
password =  *******

; 要学习的课程ID列表, 逗号隔开(选填)
#course_list = [242161289,242161005,242161223]
course_list = [242161223]

; 视频播放倍速(默认1，最大2)
speed = 2
```
**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by 41369ly** [comment]
好特殊的情况，我把我的课全扫了一遍没出现这个报错，如果方便的话你可以自己打断点看下，不过这种情况应该是加个判断跳过就行

**Comment by dong-dong6** [comment]
> 好特殊的情况，我把我的课全扫了一遍没出现这个报错，如果方便的话你可以自己打断点看下，不过这种情况应该是加个判断跳过就行

我打过了断点，我通过一个try except跳过了这个，它这个地方的类型没有匹配的判断课程截图是
![2914d8547e9eca5377764c920c5a93e](https://github.com/user-attachments/assets/c97e0365-adaa-4f95-b349-475caeb1e2af)

![55705cb130115c111844e93b23e8ae2](https://github.com/user-attachments/assets/c755655a-4bf4-4291-91c5-badea989b8e5)
