### ISSUE TITLE
docker: add dockerfile

### ISSUE THREAD

**Issue by xuhe2** [Samueli924/chaoxing#365]
# Dockerfile
```
FROM python:3.10-alpine 
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
ENTRYPOINT ["python3","main.py"]
```
- 之前的dockerfile使用python3.9版本, 不支持的python语法格式会出现以下问题
```
Traceback (most recent call last):                                                                                                                                                          
  File "/app/main.py", line 5, in <module>
    from api.base import Chaoxing, Account
  File "/app/api/base.py", line 20, in <module>
    from api.answer import *
  File "/app/api/answer.py", line 37, in <module>
    class Tiku:
  File "/app/api/answer.py", line 86, in Tiku
    def config_set(self,config:configparser.ConfigParser|None):
TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'NoneType'
```
- 使用从python.10构建的docker image可以修复这个问题

# Usage
```bash
docker run -it --rm chaoxing -u 131xxxx -p xxxxxxxx -l xxx,xxxx
```

# Q
是否接受添加dockerfile的PR?

**Comment by Samueli924** [comment]
如果方便可以帮忙提交一下PR，感谢帮助。
