### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by guayun** [Samueli924/chaoxing#378]
**代码报错截图**
![image](https://github.com/user-attachments/assets/db008965-a122-4f10-b2a2-0c5c944d9bfb)
![image](https://github.com/user-attachments/assets/4d7185b4-e533-4c82-b22f-2b143e99e0a4)

2024-11-09 15:30:44.323 | ERROR    | __main__:<module>:161 - 错误: UnboundLocalError: cannot access local variable 'q_type' where it is not associated with a value
2024-11-09 15:30:44.325 | ERROR    | __main__:<module>:162 - Traceback (most recent call last):
  File "D:\Desktop\chaoxing-main\main.py", line 152, in <module>
    chaoxing.study_work(course, job,job_info)
  File "D:\Desktop\chaoxing-main\api\base.py", line 325, in study_work
    questions = decode_questions_info(_resp.text)   # 加载题目信息
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\chaoxing-main\api\decode.py", line 216, in decode_questions_info
    'type': q_type,      # 题型 可提供给题库作为辅助
            ^^^^^^
UnboundLocalError: cannot access local variable 'q_type' where it is not associated with a value

Traceback (most recent call last):
  File "D:\Desktop\chaoxing-main\main.py", line 163, in <module>
    raise e
  File "D:\Desktop\chaoxing-main\main.py", line 152, in <module>
    chaoxing.study_work(course, job,job_info)
  File "D:\Desktop\chaoxing-main\api\base.py", line 325, in study_work
    questions = decode_questions_info(_resp.text)   # 加载题目信息
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\chaoxing-main\api\decode.py", line 216, in decode_questions_info
    'type': q_type,      # 题型 可提供给题库作为辅助
            ^^^^^^
UnboundLocalError: cannot access local variable 'q_type' where it is not associated with a value

**Comment by Samueli924** [comment]
@sz134055  q_type这是不是得加个回退机制，[ISSUE#380](https://github.com/Samueli924/chaoxing/issues/380)也有这个问题。

**Comment by Samueli924** [comment]
已合并PR
