### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by limyh01** [Samueli924/chaoxing#381]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from api.base import Chaoxing, Account
  File "/Users/limyh/chaoxing/api/base.py", line 20, in <module>
    from api.answer import *
  File "/Users/limyh/chaoxing/api/answer.py", line 37, in <module>
    class Tiku:
  File "/Users/limyh/chaoxing/api/answer.py", line 86, in Tiku
    def config_set(self,config:configparser.ConfigParser|None):
TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'NoneType'

**Comment by sz134055** [comment]
#387

**Comment by Samueli924** [comment]
已由[sz134055](https://github.com/sz134055)于[#387](https://github.com/Samueli924/chaoxing/pull/387)修复，关闭Issue

**Comment by j3gold** [comment]
> 已由[sz134055](https://github.com/sz134055)于[#387](https://github.com/Samueli924/chaoxing/pull/387)修复，关闭Issue

你好，我看最新的commit里，已经把这次提交给revert了，这是为啥呀？

**Comment by Samueli924** [comment]
我的问题，之前合并的一段代码有问题，在revert的时候多了一段，现在已经恢复
