### ISSUE TITLE
[BUG反馈] 使用tikuAdapter接口报错

### ISSUE THREAD

**Issue by ywxhqwq** [Samueli924/chaoxing#405]
**代码报错截图**
![image](https://github.com/user-attachments/assets/312c8a34-10bd-4f9c-8ee9-6a9498f9e2c4)

```
2024-12-09 06:05:31.891 | ERROR    | __main__:<module>:192 - 错误: IndexError: Cannot choose from an empty sequence
2024-12-09 06:05:31.892 | ERROR    | __main__:<module>:193 - Traceback (most recent call last):
  File "/root/chaoxing/main.py", line 183, in <module>
    chaoxing.study_work(course, job,job_info)
  File "/root/chaoxing/api/base.py", line 358, in study_work
    answer = answer if answer else random_answer(q['options'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chaoxing/api/base.py", line 261, in random_answer
    _choice = random.choice(_op_list)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

Traceback (most recent call last):
  File "/root/chaoxing/main.py", line 194, in <module>
    raise e
  File "/root/chaoxing/main.py", line 183, in <module>
    chaoxing.study_work(course, job,job_info)
  File "/root/chaoxing/api/base.py", line 358, in study_work
    answer = answer if answer else random_answer(q['options'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chaoxing/api/base.py", line 261, in random_answer
    _choice = random.choice(_op_list)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
```

使用tikuAdapter在答题时会出现这个错误

使用环境 debian11 python3.11

**Comment by ywxhqwq** [comment]
并且还有多选题只选择1个选项的问题
![image](https://github.com/user-attachments/assets/a68f24d8-db62-4823-9e8a-667b1b1d69c0)

**Comment by sz134055** [comment]
相同问题： #391

**Comment by n-WN** [comment]
同样的报错, 调试发现:报错时题目为下图中的题目

<img width="417" alt="image" src="https://github.com/user-attachments/assets/87e8cd73-410a-4c4d-aad2-9044fcb46397" />
