### ISSUE TITLE
[BUG反馈]通过config.ini配置文件无法正常启动

### ISSUE THREAD

**Issue by cclucky1** [Samueli924/chaoxing#46]
**形容Bug的信息**
[root@VM-4-4-centos chaoxing]# python3 main.py -c
[20:03:02] 启动方式：配置文件启动                                                          config.py:47
[20:03:02] 正在开始尝试登录账号                                                           getUser.py:93
           登录成功                                                                      getUser.py:108
           正在本地保存账户信息                                                          getUser.py:115
           账户信息保存成功                                                              getUser.py:118
[20:03:02] 开始获取用户的所有课程信息                                                    foreWork.py:23
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    session, jobs, course, mp4, ppt = foreWork.get_forework_done(usernm, session,courseid)
  File "/root/chaoxing/src/course/foreWork.py", line 277, in get_forework_done
    session, chapterids, course, isLocal = find_courses(usernm, session,courseid)
  File "/root/chaoxing/src/course/foreWork.py", line 68, in find_courses
    if str(item['content']['course']['data'][0]['id']) == str(courseid):
KeyError: 'course'

**Screenshots**
![image](https://user-images.githubusercontent.com/53963267/145572458-6cc2d019-0753-424b-868b-05e942cbcabf.png)
**运行环境 (请完善以下信息):**
 - 系统：CentOS7.4
 - Python环境版本:python3
 - 运行方式:源代码运行
 - 代码版本:最新

**其他内容**
通过配置文件启动时报错

**Comment by Samueli924** [comment]
已修复

**Comment by Samueli924** [comment]
可以拉取最新代码运行

**Comment by cclucky1** [comment]
拉取了最新的代码 出现了新的错误
`Traceback (most recent call last):
  File "/root/chaoxing-main/src/course/foreWork.py", line 261, in get_openc
    course['openc'] = re.findall("openc : '(.*?)'", resp.text)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    session, jobs, course, mp4, ppt = foreWork.get_forework_done(usernm, session,courseid)
  File "/root/chaoxing-main/src/course/foreWork.py", line 283, in get_forework_done
    session, course = get_openc(usernm, course, session)
  File "/root/chaoxing-main/src/course/foreWork.py", line 263, in get_openc
    course['openc'] = re.findall('&openc=(.*?)"', resp.text)[0]
IndexError: list index out of range`

**Comment by cclucky1** [comment]
拉取了最新的代码 KeyError的错误已消失，但是出现了新的错误 

仍然是在使用config.ini配置文件启动时出现

```log
Traceback (most recent call last):
  File "/root/chaoxing-main/src/course/foreWork.py", line 261, in get_openc
    course['openc'] = re.findall("openc : '(.*?)'", resp.text)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    session, jobs, course, mp4, ppt = foreWork.get_forework_done(usernm, session,courseid)
  File "/root/chaoxing-main/src/course/foreWork.py", line 283, in get_forework_done
    session, course = get_openc(usernm, course, session)
  File "/root/chaoxing-main/src/course/foreWork.py", line 263, in get_openc
    course['openc'] = re.findall('&openc=(.*?)"', resp.text)[0]
IndexError: list index out of range
```

**Comment by Samueli924** [comment]
我加了个出现错误输出请求结果的部分，麻烦你拉取一遍新代码然后把报错的完整内容发给我吧 谢谢
