### ISSUE TITLE
希望增加docker版本，處理依賴到头疼

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#50]
~/chaoxing-main ❯ pip install -r requirements.txt  
 Requirement already satisfied: requests>=2.24.0 in /home/text/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/text/.local/lib/python2.7/site-packages (from requests>=2.24.0->-r requirements.txt (line 1)) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/text/.local/lib/python2.7/site-packages (from requests>=2.24.0->-r requirements.txt (line 1)) (2021.10.8)                                                                Requirement already satisfied: idna<3,>=2.5; python_version < "3" in /home/text/.local/lib/python2.7/site-packages (from requests>=2.24.0->-r requirements.txt (line 1)) (2.10)                                                   
Requirement already satisfied: chardet<5,>=3.0.2; python_version < "3" in /home/text/.local/lib/python2.7/site-packages (from requests>=2.24.0->-r requirements.txt (line 1)) (4.0.0)

**Comment by Samueli924** [comment]
你这不是依赖问题。你这个是python2.7，建议你创建一个python3的虚拟环境运行。

**Comment by d4renk** [comment]
**_> 你这不是依赖问题。你这个是python2.7，建议你创建一个python3的虚拟环境运行。

web

Traceback (most recent call last):                                            File "web_listener.py", line 4, in <module>                                   import api                                                                File "/home/text/chaoxing_web-main/api.py", line 20                       SyntaxError: Non-ASCII character '\xe9' in file /home/text/chaoxing_web-main/api.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

main


Traceback (most recent call last):                                            File "web_listener.py", line 4, in <module>                                   import api                                                                File "/home/text/chaoxing_web-main/api.py", line 20                       SyntaxError: Non-ASCII character '\xe9' in file /home/text/chaoxing_web-main/api.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details



_**

**Comment by Samueli924** [comment]
在文件最开头加上 #coding=utf-8

**Comment by d4renk** [comment]
> 在文件最开头加上 #coding=utf-8

![Screenshot_2022_0311_090538.png](https://user-images.githubusercontent.com/64531014/157781978-9a4fe693-42c6-432f-b4c8-826625fafb47.png)
