### ISSUE TITLE
[BUG反馈]超星学习通视频节点出错

### ISSUE THREAD

**Issue by Moxiner** [Samueli924/chaoxing#51]
**形容Bug的信息**
开始做以视频形式的结点任务，main.py开始报错并停止运行

**Screenshots**
错误代码
```
Traceback (most recent call last):
  File "C:\Users\帅帅民航小辰\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\帅帅民航小辰\Desktop\chaoxing-main\main.py", line 515, in do_mp4
    resp.json()
  File "C:\Users\帅帅民航小辰\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>403</title>
<style>
.main{height:255px;margin:0 auto;margin-top:15%;font-size:14px;color:#999; width: 350px;}
.font_top{padding-top:45px;display:inline;}
</style>
</head>
<body>
<div class="main">
<p class="font_top">>_< 很抱歉，您没有权限访问这个页面！  (403)</p>
<p style="font-size: 12px; color: #ddd;">58.216.213.56<br/>mooc-3390871073-hgmpc</p>
</div>
</body>
</html>
: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\帅帅民航小辰\Desktop\chaoxing-main\main.py", line 639, in <module>
    course.do_mp4(session, speed)
  File "C:\Users\帅帅民航小辰\Desktop\chaoxing-main\main.py", line 518, in do_mp4
    raise Exception("视频任务失败")
Exception: 视频任务失败
```

**运行环境 (请完善以下信息):**
 - 系统：[Windows 10 20H2]
 - Python环境版本: [python 3.10.2]
 - 运行方式: [Powershell运行]
 - 代码版本:[v2.20]

**其他内容**
根据TrackBack推测应该是超星更新了读取视频的API，导致本程序无法正确读取视频进而报错（最近很多脚本或程序都有类似这样的Bug）

**Comment by d4renk** [comment]
[2022-03-13 22:38:13] [ERROR] 出现错误，错误类型:json.decoder.JSONDecodeError
Traceback (most recent call last):
  File "/home/text/my_env/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 516, in do_mp4
    resp.json()
  File "/home/text/my_env/lib/python3.7/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>403</title>
<style>
.main{height:255px;margin:0 auto;margin-top:15%;font-size:14px;color:#999; width: 350px;}
.font_top{padding-top:45px;display:inline;}
</style>
</head>
<body>
<div class="main">
<p class="font_top">>_< 很抱歉，您没有权限访问这个页面！  (403)</p>
<p style="font-size: 12px; color: #ddd;">121.37.10.159<br/>mooc-3390871073-3mnf2</p>
</div>
</body>
</html>
: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 640, in <module>
    course.do_mp4(session, speed)
  File "main.py", line 519, in do_mp4
    raise Exception("视频任务失败")
Exception: 视频任务失败

**Comment by 1wyy** [comment]
同问题

**Comment by Samueli924** [comment]
预计将在两周内更新代码
