### ISSUE TITLE
[严重的BUG反馈] 读取课程时抛出KeyError，导致程序终止

### ISSUE THREAD

**Issue by Moxiner** [Samueli924/chaoxing#58]
**形容Bug的信息**
读取课程时抛出KeyError，导致程序终止
```
请输入要登录的用户序号，新建请输入直接点击回车键1
2022-04-05 15:48:54,182 - main - INFO - 开始登录
2022-04-05 15:48:56,444 - main - INFO - 开始读取所有课程
2022-04-05 15:49:00,559 - main - INFO - 开始选课
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, 
in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\帅帅民航小辰\.vscode\extensions\ms-python.python-2022.4.0\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\帅帅民航小辰\.vscode\extensions\ms-python.python-2022.4.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\帅帅民航小辰\.vscode\extensions\ms-python.python-2022.4.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 269, 
in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\帅帅民航小辰\Desktop\chaoxing-main\main.py", line 77, in <module>
    if chaoxing.select_course():    # 选择要学习的课程
  File "c:\Users\帅帅民航小辰\Desktop\chaoxing-main\api\chaoxing.py", line 82, in select_course
    pretty_print(self.courses)
  File "c:\Users\帅帅民航小辰\Desktop\chaoxing-main\utils\functions.py", line 155, in pretty_print
    data.append([str(course_index + 1), str(course["key"]), str(course['content']['course']['data'][0]['name'])])
KeyError: 'course'
```
**Debug截图**
![这是一个图片](https://user-images.githubusercontent.com/87905048/161712535-4d485064-b164-4da9-b37c-f4ed1e74bb8f.png)

**运行环境 (请完善以下信息):**
 - 系统：[Windows 10]
 - Python环境版本: [Python 3.10.4]
 - 运行方式: [源代码运行、可执行文件exe运行]
 - 代码版本:[2.31]

**其他内容**
我检查部分代码，变量 Key:course 并没有 课程名称（瞎猜）
预测是学习通更新导致 （也有可能是咱技术不够）
以下是我在Debug中查找的 变量 Key:course
```
{
    'cfid': -1, 
    'catalogId': 1458887, 
    'cataid': '100000017', 
    'key': 1458887, '
    content': {
        'cfid': 1458887, 
        'uid': '170930724', 
        'createtime': 1621939782000, 
        'puid': '170930724', 'pid': 0, 
        'folderName': '弃修', 
        'cpi': 181112899, 
        'shareType': 10
        }
    }
```

**Comment by Samueli924** [comment]
感谢你的详细反馈。我在最新commit中跳过了没有course键的课程，我觉得可能是因为存在一些特殊情况的课程，比如课程被删除了，但还是能够搜索到。
